version: '3'

services:
  php-fpm:
    image: 10up/phpfpm:7.2
    depends_on:
      - db
    volumes:
      - "./wordpress:/var/www/html"
      - "./content:/var/www/html/wp-content"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    restart: always

  nginx:
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - "./wordpress:/var/www/html"
      - "./content:/var/www/html/wp-content"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always

  db:
    image: mariadb
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILCATCHER_PORT: 1025
